services:
  - type: web
    name: grade-my-mail
    runtime: node
    buildCommand: npm ci && npm run build && npm run build:server
    startCommand: node dist/server/index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
      - key: HOST
        value: "0.0.0.0"