services:
  - type: web
    name: grade-my-mail
    runtime: node
    buildCommand: npm install && npm run build && tsc -p server/tsconfig.production.json
    startCommand: node dist/server/index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"